In [4]:
###### Ignore this!
!import pytest
!import hashlib
_ = 123456789  # just a wrong number, please ignore
###### Stop ignoring

import numpy as np

# Metabolic Flux Analysis

# 1. Write down the stoichiometry matrix S for the model as a numpy array.
# The order of the rows should correspond to A, B and C.
# The order of the columns should correspond to v1-v6


# replace [[]] with the stoichiometric matrix.
S = np.array([[-1, -1, 0, 0, 0, 1], [1,  0, 0, 0,-1, 0],[0, 1, -1, -1, 0, 0]])

###### Don't touch
def test_stoichiometry_matrix():
    assert hashlib.md5(S).digest() == b'\xe2Q(\xd6\xf1\x8f.7F\xfbB(\xabY\xf8\xcc'
###### this


# 2. Calculate how many fluxes need to be measured (degrees of freedom).

# Assign your solution to the following variable (replace _ with your solution;
# cannot be just a number; should be a computation based on S)
from numpy.linalg import matrix_rank
degrees_of_freedom = S.shape[1] - matrix_rank(S)


###### Don't touch
def test_degrees_of_freedom():
    assert degrees_of_freedom == 3
###### this


# 3. Based on measured fluxes v4 = 2.5, v5 = 2, and v6 = 10, calculate v1-v3.

# Put you're intermediate steps here ...

S_c = S[:, 0:3] #matrix with the unknow fluxes
S_m = S[:, 3:] #matrix with the known fluxes
v_m = np.array([2.5, 2, 10]) # v4, v5, v6

# Assign the final solution here (replace _ with your final step)
# v_c needs to be a numpy.array containing the three calculated fluxes v1-v3
# Ideally you should get to v_c through a computation involving S and the
# measured fluxes v4-v6 as covered in the lecture.

v_c = -np.linalg.inv(S_c).dot(S_m.dot(v_m))

###### Don't touch
def test_mfa_calculation():
    assert v_c.sum() == 15.5
###### this

import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.


In [5]:
import numpy as np

In [6]:
S = np.array([[-1, -1, 0, 0, 0, 1], [1,  0, 0, 0,-1, 0],[0, 1, -1, -1, 0, 0]])

In [7]:
from numpy.linalg import matrix_rank

In [8]:
degrees_of_freedom = S.shape[1] - matrix_rank(S)

In [10]:
print(degrees_of_freedom)

3


In [11]:
S_c = S[:, 0:3] #matrix with the unknow fluxes
S_m = S[:, 3:] #matrix with the known fluxes
v_m = np.array([2.5, 2, 10]) # v4, v5

In [12]:
print(S_c,S_m,v_m)

[[-1 -1  0]
 [ 1  0  0]
 [ 0  1 -1]] [[ 0  0  1]
 [ 0 -1  0]
 [-1  0  0]] [ 2.5  2.  10. ]
